site_name: Plotly Libraries
site_description: Documentation for Plotly libraries
site_url: https://example.com
copyright: Plotly Inc.

docs_dir: src
site_dir: docs
theme:
  name: null
  custom_dir: theme

nav:
  - Home: index.md
  - About: about.md

plugins:
  - rss:
      date_from_meta:
        as_creation: "date"
        datetime_format: "%Y-%m-%dT%H:%M:%S"
      json_feed_enabled: true
      rss_feed_enabled: false
      feeds_filenames:
        json_created: feed_json_updated.json
      match_path: "blog/.*"
      use_git: false

algolia:
  application_id: '7EK9KHJW8M'
  index_name: 'python_docs'
  read_only_api_key: '4dae07ded6a721de73bde7356eec9280'
  excluded_files:
    - '*.png'
    - '*.Rmd'
    - '*.R'
    - '_posts/dashboards'
    - '_posts/ggplot2'
    - '_posts/julia'
    - '_posts/matlab'
    - '_posts/misc'
    - '_posts/nodejs'
    - '_posts/plotly_js'
    - '_posts/r'
    - '_posts/reference_pages'
    - '_posts/scala'
    - '_posts/temp'
  settings:
    attributesToIndex:
      - name
      - description
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
